// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: model/pb/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time     uint32  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Open     float32 `protobuf:"fixed32,2,opt,name=open,proto3" json:"open,omitempty"`
	Close    float32 `protobuf:"fixed32,3,opt,name=close,proto3" json:"close,omitempty"`
	High     float32 `protobuf:"fixed32,4,opt,name=high,proto3" json:"high,omitempty"`
	Low      float32 `protobuf:"fixed32,5,opt,name=low,proto3" json:"low,omitempty"`
	Volume   float64 `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Turnover float64 `protobuf:"fixed64,7,opt,name=turnover,proto3" json:"turnover,omitempty"`
}

func (x *KData) Reset() {
	*x = KData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_pb_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KData) ProtoMessage() {}

func (x *KData) ProtoReflect() protoreflect.Message {
	mi := &file_model_pb_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KData.ProtoReflect.Descriptor instead.
func (*KData) Descriptor() ([]byte, []int) {
	return file_model_pb_data_proto_rawDescGZIP(), []int{0}
}

func (x *KData) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *KData) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *KData) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *KData) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *KData) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *KData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *KData) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

type XData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date        uint32  `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	AllotVolume float32 `protobuf:"fixed32,2,opt,name=allotVolume,proto3" json:"allotVolume,omitempty"`
	AllotPrice  float32 `protobuf:"fixed32,3,opt,name=allotPrice,proto3" json:"allotPrice,omitempty"`
	BonusVolume float32 `protobuf:"fixed32,4,opt,name=bonusVolume,proto3" json:"bonusVolume,omitempty"`
	BonusPrice  float32 `protobuf:"fixed32,5,opt,name=bonusPrice,proto3" json:"bonusPrice,omitempty"`
}

func (x *XData) Reset() {
	*x = XData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_pb_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XData) ProtoMessage() {}

func (x *XData) ProtoReflect() protoreflect.Message {
	mi := &file_model_pb_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XData.ProtoReflect.Descriptor instead.
func (*XData) Descriptor() ([]byte, []int) {
	return file_model_pb_data_proto_rawDescGZIP(), []int{1}
}

func (x *XData) GetDate() uint32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *XData) GetAllotVolume() float32 {
	if x != nil {
		return x.AllotVolume
	}
	return 0
}

func (x *XData) GetAllotPrice() float32 {
	if x != nil {
		return x.AllotPrice
	}
	return 0
}

func (x *XData) GetBonusVolume() float32 {
	if x != nil {
		return x.BonusVolume
	}
	return 0
}

func (x *XData) GetBonusPrice() float32 {
	if x != nil {
		return x.BonusPrice
	}
	return 0
}

type VData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date     uint32  `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Tradable float64 `protobuf:"fixed64,2,opt,name=tradable,proto3" json:"tradable,omitempty"`
	Total    float64 `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *VData) Reset() {
	*x = VData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_pb_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VData) ProtoMessage() {}

func (x *VData) ProtoReflect() protoreflect.Message {
	mi := &file_model_pb_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VData.ProtoReflect.Descriptor instead.
func (*VData) Descriptor() ([]byte, []int) {
	return file_model_pb_data_proto_rawDescGZIP(), []int{2}
}

func (x *VData) GetDate() uint32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *VData) GetTradable() float64 {
	if x != nil {
		return x.Tradable
	}
	return 0
}

func (x *VData) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_model_pb_data_proto protoreflect.FileDescriptor

var file_model_pb_data_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9f, 0x01, 0x0a, 0x05, 0x4b, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x22, 0x9f, 0x01, 0x0a, 0x05,
	0x58, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6c, 0x6c,
	0x6f, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x6c, 0x6c, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x6f, 0x6e, 0x75, 0x73, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x4d, 0x0a,
	0x05, 0x56, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x72,
	0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_pb_data_proto_rawDescOnce sync.Once
	file_model_pb_data_proto_rawDescData = file_model_pb_data_proto_rawDesc
)

func file_model_pb_data_proto_rawDescGZIP() []byte {
	file_model_pb_data_proto_rawDescOnce.Do(func() {
		file_model_pb_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_pb_data_proto_rawDescData)
	})
	return file_model_pb_data_proto_rawDescData
}

var file_model_pb_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_pb_data_proto_goTypes = []interface{}{
	(*KData)(nil), // 0: pb.KData
	(*XData)(nil), // 1: pb.XData
	(*VData)(nil), // 2: pb.VData
}
var file_model_pb_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_pb_data_proto_init() }
func file_model_pb_data_proto_init() {
	if File_model_pb_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_pb_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_pb_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_pb_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_pb_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_pb_data_proto_goTypes,
		DependencyIndexes: file_model_pb_data_proto_depIdxs,
		MessageInfos:      file_model_pb_data_proto_msgTypes,
	}.Build()
	File_model_pb_data_proto = out.File
	file_model_pb_data_proto_rawDesc = nil
	file_model_pb_data_proto_goTypes = nil
	file_model_pb_data_proto_depIdxs = nil
}
