// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/api_model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XDataType int32

const (
	XData_XDR XDataType = 0
	XData_EXP XDataType = 1
)

// Enum value maps for XDataType.
var (
	XDataType_name = map[int32]string{
		0: "XDR",
		1: "EXP",
	}
	XDataType_value = map[string]int32{
		"XDR": 0,
		"EXP": 1,
	}
)

func (x XDataType) Enum() *XDataType {
	p := new(XDataType)
	*p = x
	return p
}

func (x XDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_model_proto_enumTypes[0].Descriptor()
}

func (XDataType) Type() protoreflect.EnumType {
	return &file_api_api_model_proto_enumTypes[0]
}

func (x XDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XDataType.Descriptor instead.
func (XDataType) EnumDescriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{1, 0}
}

type VDataType int32

const (
	VData_NONE VDataType = 0
)

// Enum value maps for VDataType.
var (
	VDataType_name = map[int32]string{
		0: "NONE",
	}
	VDataType_value = map[string]int32{
		"NONE": 0,
	}
)

func (x VDataType) Enum() *VDataType {
	p := new(VDataType)
	*p = x
	return p
}

func (x VDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_model_proto_enumTypes[1].Descriptor()
}

func (VDataType) Type() protoreflect.EnumType {
	return &file_api_api_model_proto_enumTypes[1]
}

func (x VDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VDataType.Descriptor instead.
func (VDataType) EnumDescriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{2, 0}
}

type KData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string  `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Time     uint32  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Open     float32 `protobuf:"fixed32,3,opt,name=Open,proto3" json:"Open,omitempty"`
	Close    float32 `protobuf:"fixed32,4,opt,name=Close,proto3" json:"Close,omitempty"`
	High     float32 `protobuf:"fixed32,5,opt,name=High,proto3" json:"High,omitempty"`
	Low      float32 `protobuf:"fixed32,6,opt,name=Low,proto3" json:"Low,omitempty"`
	Volume   float64 `protobuf:"fixed64,7,opt,name=Volume,proto3" json:"Volume,omitempty"`
	Turnover float64 `protobuf:"fixed64,8,opt,name=Turnover,proto3" json:"Turnover,omitempty"`
}

func (x *KData) Reset() {
	*x = KData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KData) ProtoMessage() {}

func (x *KData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KData.ProtoReflect.Descriptor instead.
func (*KData) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{0}
}

func (x *KData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KData) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *KData) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *KData) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *KData) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *KData) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *KData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *KData) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

type XData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date        uint32    `protobuf:"varint,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Type        XDataType `protobuf:"varint,2,opt,name=Type,proto3,enum=pb.XDataType" json:"Type,omitempty"`
	AllotVolume float32   `protobuf:"fixed32,3,opt,name=AllotVolume,proto3" json:"AllotVolume,omitempty"`
	AllotPrice  float32   `protobuf:"fixed32,4,opt,name=AllotPrice,proto3" json:"AllotPrice,omitempty"`
	BonusVolume float32   `protobuf:"fixed32,5,opt,name=BonusVolume,proto3" json:"BonusVolume,omitempty"`
	BonusPrice  float32   `protobuf:"fixed32,6,opt,name=BonusPrice,proto3" json:"BonusPrice,omitempty"`
}

func (x *XData) Reset() {
	*x = XData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XData) ProtoMessage() {}

func (x *XData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XData.ProtoReflect.Descriptor instead.
func (*XData) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{1}
}

func (x *XData) GetDate() uint32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *XData) GetType() XDataType {
	if x != nil {
		return x.Type
	}
	return XData_XDR
}

func (x *XData) GetAllotVolume() float32 {
	if x != nil {
		return x.AllotVolume
	}
	return 0
}

func (x *XData) GetAllotPrice() float32 {
	if x != nil {
		return x.AllotPrice
	}
	return 0
}

func (x *XData) GetBonusVolume() float32 {
	if x != nil {
		return x.BonusVolume
	}
	return 0
}

func (x *XData) GetBonusPrice() float32 {
	if x != nil {
		return x.BonusPrice
	}
	return 0
}

type VData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date         uint32    `protobuf:"varint,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Type         VDataType `protobuf:"varint,2,opt,name=Type,proto3,enum=pb.VDataType" json:"Type,omitempty"`
	PreTradable  float64   `protobuf:"fixed64,3,opt,name=preTradable,proto3" json:"preTradable,omitempty"`
	PreTotal     float64   `protobuf:"fixed64,4,opt,name=preTotal,proto3" json:"preTotal,omitempty"`
	PostTradable float64   `protobuf:"fixed64,5,opt,name=postTradable,proto3" json:"postTradable,omitempty"`
	PostTotal    float64   `protobuf:"fixed64,6,opt,name=postTotal,proto3" json:"postTotal,omitempty"`
}

func (x *VData) Reset() {
	*x = VData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VData) ProtoMessage() {}

func (x *VData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VData.ProtoReflect.Descriptor instead.
func (*VData) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{2}
}

func (x *VData) GetDate() uint32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *VData) GetType() VDataType {
	if x != nil {
		return x.Type
	}
	return VData_NONE
}

func (x *VData) GetPreTradable() float64 {
	if x != nil {
		return x.PreTradable
	}
	return 0
}

func (x *VData) GetPreTotal() float64 {
	if x != nil {
		return x.PreTotal
	}
	return 0
}

func (x *VData) GetPostTradable() float64 {
	if x != nil {
		return x.PostTradable
	}
	return 0
}

func (x *VData) GetPostTotal() float64 {
	if x != nil {
		return x.PostTotal
	}
	return 0
}

type PutLdayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*KData `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PutLdayRequest) Reset() {
	*x = PutLdayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutLdayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLdayRequest) ProtoMessage() {}

func (x *PutLdayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLdayRequest.ProtoReflect.Descriptor instead.
func (*PutLdayRequest) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{3}
}

func (x *PutLdayRequest) GetData() []*KData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutXDRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Data []*XData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PutXDRRequest) Reset() {
	*x = PutXDRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutXDRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutXDRRequest) ProtoMessage() {}

func (x *PutXDRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutXDRRequest.ProtoReflect.Descriptor instead.
func (*PutXDRRequest) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{4}
}

func (x *PutXDRRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PutXDRRequest) GetData() []*XData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutVolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Data []*VData `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PutVolRequest) Reset() {
	*x = PutVolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutVolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVolRequest) ProtoMessage() {}

func (x *PutVolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVolRequest.ProtoReflect.Descriptor instead.
func (*PutVolRequest) Descriptor() ([]byte, []int) {
	return file_api_api_model_proto_rawDescGZIP(), []int{5}
}

func (x *PutVolRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PutVolRequest) GetData() []*VData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_api_model_proto protoreflect.FileDescriptor

var file_api_api_model_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xb3, 0x01, 0x0a, 0x05, 0x4b, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4f,
	0x70, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x48, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x77,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x4c, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x22,
	0xdd, 0x01, 0x0a, 0x05, 0x58, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x58, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x42, 0x6f, 0x6e, 0x75, 0x73,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x18, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a,
	0x03, 0x58, 0x44, 0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x58, 0x50, 0x10, 0x01, 0x22,
	0xd1, 0x01, 0x0a, 0x05, 0x56, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x72, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x72, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x10, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x22, 0x2f, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4c, 0x64, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x58, 0x44, 0x52, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x58, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x56,
	0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x56, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_model_proto_rawDescOnce sync.Once
	file_api_api_model_proto_rawDescData = file_api_api_model_proto_rawDesc
)

func file_api_api_model_proto_rawDescGZIP() []byte {
	file_api_api_model_proto_rawDescOnce.Do(func() {
		file_api_api_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_model_proto_rawDescData)
	})
	return file_api_api_model_proto_rawDescData
}

var file_api_api_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_api_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_api_model_proto_goTypes = []interface{}{
	(XDataType)(0),         // 0: pb.XData.type
	(VDataType)(0),         // 1: pb.VData.type
	(*KData)(nil),          // 2: pb.KData
	(*XData)(nil),          // 3: pb.XData
	(*VData)(nil),          // 4: pb.VData
	(*PutLdayRequest)(nil), // 5: pb.PutLdayRequest
	(*PutXDRRequest)(nil),  // 6: pb.PutXDRRequest
	(*PutVolRequest)(nil),  // 7: pb.PutVolRequest
}
var file_api_api_model_proto_depIdxs = []int32{
	0, // 0: pb.XData.Type:type_name -> pb.XData.type
	1, // 1: pb.VData.Type:type_name -> pb.VData.type
	2, // 2: pb.PutLdayRequest.Data:type_name -> pb.KData
	3, // 3: pb.PutXDRRequest.Data:type_name -> pb.XData
	4, // 4: pb.PutVolRequest.Data:type_name -> pb.VData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_api_model_proto_init() }
func file_api_api_model_proto_init() {
	if File_api_api_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutLdayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutXDRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutVolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_model_proto_goTypes,
		DependencyIndexes: file_api_api_model_proto_depIdxs,
		EnumInfos:         file_api_api_model_proto_enumTypes,
		MessageInfos:      file_api_api_model_proto_msgTypes,
	}.Build()
	File_api_api_model_proto = out.File
	file_api_api_model_proto_rawDesc = nil
	file_api_api_model_proto_goTypes = nil
	file_api_api_model_proto_depIdxs = nil
}
